// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-9bdt_zqY8MPAaHc_ShKtBPa7R22Fd5k',
    appId: '1:65147188603:web:360e07fd0f32582cc139de',
    messagingSenderId: '65147188603',
    projectId: 'mynotes-34',
    authDomain: 'mynotes-34.firebaseapp.com',
    storageBucket: 'mynotes-34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGKnnAKQmzwwr_SzLvsgay1Px-cfRpFds',
    appId: '1:65147188603:android:519f1d0b7828dcf2c139de',
    messagingSenderId: '65147188603',
    projectId: 'mynotes-34',
    storageBucket: 'mynotes-34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtm7_LQPPNXBJMvNokTlXqvASqy_kzFOE',
    appId: '1:65147188603:ios:64c354e1da1b4f69c139de',
    messagingSenderId: '65147188603',
    projectId: 'mynotes-34',
    storageBucket: 'mynotes-34.appspot.com',
    iosClientId: '65147188603-g408c7o521svhhmg17et4qsep3nfc8du.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtm7_LQPPNXBJMvNokTlXqvASqy_kzFOE',
    appId: '1:65147188603:ios:64c354e1da1b4f69c139de',
    messagingSenderId: '65147188603',
    projectId: 'mynotes-34',
    storageBucket: 'mynotes-34.appspot.com',
    iosClientId: '65147188603-g408c7o521svhhmg17et4qsep3nfc8du.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
